#!/usr/bin/env bash
# wal-gradience.sh
# Reads pywal's colors.json and writes wal colors directly to
# ~/.config/gtk-3.0/gtk.css and ~/.config/gtk-4.0/gtk.css,
# bypassing Gradience CLI entirely.
#
# Hook into pywal:
#   wal -i wallpaper.jpg -n -q -o ~/.config/wal/wal-gradience.sh

WAL_COLORS="$HOME/.cache/wal/colors.json"
GTK3_CSS="$HOME/.config/gtk-3.0/gtk.css"
GTK4_CSS="$HOME/.config/gtk-4.0/gtk.css"

if [ ! -f "$WAL_COLORS" ]; then
    echo "Error: $WAL_COLORS not found. Run pywal first."
    exit 1
fi

mkdir -p "$HOME/.config/gtk-3.0"
mkdir -p "$HOME/.config/gtk-4.0"

# Generate CSS from pywal colors.json
python3 << EOF
import json

with open("$WAL_COLORS") as f:
    wal = json.load(f)

c = wal["colors"]

css = """/* Generated by wal-gradience.sh — do not edit manually */
@define-color accent_color             {color4};
@define-color accent_bg_color          {color5};
@define-color accent_fg_color          {color7};
@define-color destructive_color        {color2};
@define-color destructive_bg_color     {color2};
@define-color destructive_fg_color     {color0};
@define-color success_color            {color6};
@define-color success_bg_color         {color6};
@define-color success_fg_color         {color0};
@define-color warning_color            {color3};
@define-color warning_bg_color         {color3};
@define-color warning_fg_color         {color0};
@define-color error_color              {color2};
@define-color error_bg_color           {color2};
@define-color error_fg_color           {color0};
@define-color window_bg_color          {color0};
@define-color window_fg_color          {color7};
@define-color view_bg_color            {color0};
@define-color view_fg_color            {color7};
@define-color headerbar_bg_color       {color0};
@define-color headerbar_fg_color       {color7};
@define-color headerbar_border_color   {color8};
@define-color headerbar_backdrop_color {color0};
@define-color headerbar_shade_color    {color0};
@define-color card_bg_color            {color1};
@define-color card_fg_color            {color7};
@define-color card_shade_color         {color0};
@define-color dialog_bg_color          {color1};
@define-color dialog_fg_color          {color7};
@define-color popover_bg_color         {color1};
@define-color popover_fg_color         {color7};
@define-color shade_color              {color0};
@define-color scrollbar_outline_color  {color8};
""".format(
    color0=c["color0"],
    color1=c["color1"],
    color2=c["color2"],
    color3=c["color3"],
    color4=c["color4"],
    color5=c["color5"],
    color6=c["color6"],
    color7=c["color7"],
    color8=c["color8"],
)

for path in ["$GTK3_CSS", "$GTK4_CSS"]:
    with open(path, "w") as f:
        f.write(css)
    print(f"Written: {path}")
EOF

# Force GTK to not use a named theme so our gtk.css takes effect
gsettings set org.gnome.desktop.interface gtk-theme '' 2>/dev/null
gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark' 2>/dev/null

echo "GTK3 and GTK4 themes updated from pywal colors."